### ISSUE TITLE
paper code

### ISSUE THREAD

**Issue by hila-sony** [bob831009/raw_image_deblurring#7]
Hi,
Is the code of the deblurring method presented in the paper available somewhere?

**Comment by bob831009** [comment]
Hi,
Thanks for your interest in the publication. However, we cannot release the source code due to confidential considerations. As all the layers are supported by PyTorch, we believe you can reproduce the model architecture easily via the information provided in the paper. Still thanks for your interest. If there is any other thing we can help with, please feel free to let us know. Thanks!

**Comment by hila-sony** [comment]
OK, thanks for your quick reply!
